# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IBPSA Project 1
email: MWetter@lbl.gov
description: > # this means to ignore newlines until "baseurl:"
  BIM/GIS and Modelica framework for building and community energy system design and operation
baseurl: "/project1" # the subpath of your site, e.g. /blog
url: "http://ibpsa.github.io/project1" # the base hostname & protocol for your site
twitter_username:
github_username:  ibpsa/project1

include: ['_posts']
future: true
# Build settings
markdown: kramdown
